name: conda_env

channels:
  - conda-forge

dependencies:
  - python >= 3.14
  - conan
  - gcc=16.*
  - gxx=16.*
  - m2w64-sysroot_win-64 # [win]
  - binutils
  - libgcc
  - libstdcxx
  - cmake
  - ninja

  - gcovr
  - clang-tools
