name: Release Packaging

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package all project files
        run: |
          mkdir -p package

          rsync -a --exclude package --exclude .git ./ build_menu/

          zip -r build_menu_package.zip build_menu

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_menu_package
          path: build_menu_package.zip
